"""Losts Migration

Revision ID: 19a56c01fa58
Revises: 84387f94891f
Create Date: 2019-10-01 15:03:02.327914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a56c01fa58'
down_revision = '84387f94891f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('lost', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('lost', 'name')
    op.drop_column('lost', 'address')
    # ### end Alembic commands ###
