"""Found Migration

Revision ID: 240a8241654c
Revises: 98bcd51f9efc
Create Date: 2019-10-02 12:00:52.719933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240a8241654c'
down_revision = '98bcd51f9efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('found',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('found')
    # ### end Alembic commands ###
