"""date  Migration

Revision ID: 489515ec28f6
Revises: 998d9416129b
Create Date: 2019-10-03 09:21:57.642464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489515ec28f6'
down_revision = '998d9416129b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fouid = db.Column(db.Integer, primary_key = True)nd', sa.Column('posted_date', sa.Integer(), nullable=True))
    op.add_column('lost', sa.Column('posted_date', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lost', 'posted_date')
    op.drop_column('fouid = db.Column(db.Integer, primary_key = True)nd', 'posted_date')
    # ### end Alembic commands ###
