"""description  Migration

Revision ID: 5104a3b935a7
Revises: cac0d74213a9
Create Date: 2019-10-02 14:34:01.815763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5104a3b935a7'
down_revision = 'cac0d74213a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lost', 'description')
    # ### end Alembic commands ###
