"""Image Migration

Revision ID: 98bcd51f9efc
Revises: 19a56c01fa58
Create Date: 2019-10-02 09:57:20.560395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bcd51f9efc'
down_revision = '19a56c01fa58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost', sa.Column('image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lost', 'image')
    # ### end Alembic commands ###
