"""found  Migration

Revision ID: 998d9416129b
Revises: d5e645a99a71
Create Date: 2019-10-02 15:20:09.686273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998d9416129b'
down_revision = 'd5e645a99a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fouid = db.Column(db.Integer, primary_key = True)nd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('f_name', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lost_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lost_id'], ['lost.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fouid = db.Column(db.Integer, primary_key = True)nd_category'), 'fouid = db.Column(db.Integer, primary_key = True)nd', ['category'], unique=False)
    op.drop_table('found')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('found',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lost_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lost_id'], ['lost.id'], name='found_lost_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='found_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='found_pkey')
    )
    op.drop_index(op.f('ix_fouid = db.Column(db.Integer, primary_key = True)nd_category'), table_name='fouid = db.Column(db.Integer, primary_key = True)nd')
    op.drop_table('fouid = db.Column(db.Integer, primary_key = True)nd')
    # ### end Alembic commands ###
