"""added to found Migration

Revision ID: 9bf786d46ef3
Revises: 240a8241654c
Create Date: 2019-10-02 12:10:25.410240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf786d46ef3'
down_revision = '240a8241654c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('lost', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lost', 'phone')
    op.drop_column('lost', 'location')
    # ### end Alembic commands ###
