"""photo  Migration

Revision ID: d5e645a99a71
Revises: 5104a3b935a7
Create Date: 2019-10-02 14:53:30.072901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e645a99a71'
down_revision = '5104a3b935a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lost', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost', sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
